apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: bot-prod

configMapGenerator:
  - name: voice-bank-bot-config
    behavior: merge # dopisz/nadpisz klucze z base
    literals:
      - MODEL_NAME=gpt-4o
      - TTS_VOICE=nova

patches:
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: voice-bank-bot
      spec:
        minReplicas: 3
