apiVersion: v1
kind: Namespace
metadata:
  name: bot-dev
  labels:
    env: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: bot-prod
  labels:
    env: prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: bot-staging
  labels:
    env: staging
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: bot-quota
  namespace: bot-dev # quota działa tylko w tym namespace
spec:
  hard:
    requests.cpu: 700m # 2 pody po 200m się mieszczą, trzeci już nie
    requests.memory: 1Gi